# -*- coding: utf-8 -*-
"""SimpleLinear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-i5f0wJTXTVj-g3CIhZsqsgoEE_vjjf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

sample = pd.read_csv("/content/singlevarible.csv")# Read Csv File

sample

obj = linear_model.LinearRegression()# Create a object For LinearRegression()

obj.fit(sample[['Area']],sample.Price)# Train the Data's

obj.predict([[3300]])# Predict the Price

plt.xlabel('Area',fontsize=20)#Xlabel
plt.ylabel('Price',fontsize=20)#Ylabel
plt.scatter(sample.Area,sample.Price,color="blue",marker="+")#Scatter Plot
plt.plot(sample.Area,obj.predict(sample[['Area']]),color='red')#Regression Line

obj.coef_#Coffeicent

obj.intercept_#Intercept

#The Simple Linear Regression Formula
# y=mx+c
#y=Dependent Variable
#m=coefficent
#x=Independent Variable
#c=Intercept

Price = 135.78767123*3300+180616.43835616432

print(Price)